### ISSUE TITLE
✨ feat: 소셜로그인+JWT 개발 

### ISSUE THREAD

**Issue by softwareyong** [ktb-cpplab/cpplab-be#4]
# Title
- 소셜로그인+JWT 개발 

# TODO

- [x] (카카오,네이버) 로그인
- [x] 프론트에서 로그인 시도에서 헤더로 엑세스 토큰받기
- [x] refresh rotate 도입(엑세스, 리프레시 expire 같은 주기)
- [x] 로그아웃
- [x] 쿠키, 리프레시 토큰) 제거
- [x] 서버 mysql 리프레시 토큰 제거
- [x] reissue 도입(사용 중 엑세스 토큰 만료 시, 엑세스 토큰 재발급)

# etc [프론트 확인]
![image](https://github.com/user-attachments/assets/2c81f71c-0e34-4a5e-80f7-ed67e5e688a2)
- 하이퍼링크로 로그인을 요청하기 때문에 프론트 상태관리를 위해서 useeffect로 api 재요청 로직 필요
